## Voltando à tabela salarial

Rode os códigos abaixo, considerando o arquivo TabelaSalarial.csv e responda às perguntas ao final.

In [40]:
import pandas as pd
dados = pd.read_csv('TabelaSalarial.csv')
dados.head()

,N,Estado Civil,Grau de Instrução,N de Filhos,Salario (x Sal Min),Idade (em anos),Região de Procedência
0,1,solteiro,ensino fundamental,NaN,4.00,26,interior
1,2,casado,ensino fundamental,1.0,4.56,32,capital
2,3,casado,ensino fundamental,2.0,5.25,36,capital
3,4,solteiro,ensino médio,NaN,5.73,20,outra
4,5,solteiro,ensino fundamental,NaN,6.26,40,outra

In [41]:
import matplotlib
dados.describe()

               N  N de Filhos  Salario (x Sal Min)  Idade (em anos)
count  36.000000    20.000000            36.000000        36.000000
mean   18.500000     1.650000            11.122222        34.583333
std    10.535654     1.268028             4.587458         6.737422
min     1.000000     0.000000             4.000000        20.000000
25%     9.750000     1.000000             7.552500        30.000000
50%    18.500000     2.000000            10.165000        34.500000
75%    27.250000     2.000000            14.060000        40.000000
max    36.000000     5.000000            23.300000        48.000000

## Perguntas:

1) o que faz o código acima (dados.describe())?

2) Quais informações são apresentadas?

3) Todas as variáveis têm o mesmo número de informações?

4) O que significa a variável "mean" e "std"?

5) Considerando o o máximo, o mínimo, a média e o "std", o que podemos inferir sobre as variáveis nº de filhos, salário e idade?

6) Por que não aparecem as variáveis "Grau de instrução" e "Região de Procedência"?

7) Considerando todas as análises e informações coletadas, a média é um bom indicativo para os dados?

8) Calcule a mediana e a moda dos dados apresentados na saída dados.describe(). Os valores encontrados são próximos à média?

1 O comando dados.describe() cria uma tabela rápida com dados sobre o arquivo.

2 Apresenta as informações quantitativas da tabela. Como:

3 Não, na variável número de filhos, de todas as 36 pessoas que responderam a pesquisa a variável apresenta apenas 20 respostas.

4 Média e desvio do padrão.

5 O desvio padrão mostra o quão fielmente a média representa os valores na tabela, quanto mais próximo de 0 o valor do desvio padrão, mais acertiva será a média

6 A função describe() mostra apenas dados quantitativos.

7 Não, a média em alguns casos pode apresentar valores fora da realidade, dependendo dos valores mínimos e máximos apresentados na tabela.

8 Segue código abaixo:

In [47]:
medianafilhos = dados['N de Filhos'].median()
medianasalario = dados['Salario (x Sal Min)'].median()
medianaidade = dados['Idade (em anos)'].median()
print('a mediana do número de filhos é: ', medianafilhos)
print('a mediana do salário com base no salário mínimo é: ', medianasalario)
print('a mediana da idade é: ', medianaidade)
modafilhos = dados['N de Filhos'].mode().iloc[0]
modasalario = dados['Salario (x Sal Min)'].mode().iloc[0]
modaidade = dados['Idade (em anos)'].mode().iloc[0]
print('a moda do número de filhos é: ', modafilhos)
print('a moda do salário com base no salário mínimo é: ', modasalario)
print('a moda da idade é: ', modaidade)

a mediana do número de filhos é:  2.0
a mediana do salário com base no salário mínimo é:  10.165
a mediana da idade é:  34.5
a moda do número de filhos é:  2.0
a moda do salário com base no salário mínimo é:  4.0
a moda da idade é:  26